version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    ignore:
      # until issue azeemba/eslint-plugin-json#97 is fixed
      - dependency-name: 'eslint'
        versions: ['10.x']
